# Define the API version and resource type
apiVersion: apps/v1                  # API version for Deployment objects
kind: Deployment                     # This resource is a Deployment

metadata:
  name: frontend                     # Name of the Deployment
  namespace: nimc-demo               # Namespace where the Deployment will be created
  labels:                            # Key-value pairs to identify the Deployment
    app: frontend
    tier: web

spec:
  replicas: 2                        # Number of pod replicas to run
  selector:                          # Defines how the Deployment finds which Pods to manage
    matchLabels:
      app: frontend                  # Must match the labels in pod template

  template:                          # Pod template that defines how the pods should be created
    metadata:
      labels:                        # Labels assigned to Pods created by this Deployment
        app: frontend
        tier: web
    spec:
      containers:
      - name: frontend               # Container name inside the pod
        image: successtech/bcf8:v1  # Docker image to deploy
        ports:
        - containerPort: 80          # Exposes port 80 inside the container (HTTP)
        resources:                   # Resource requests and limits for scheduler
          requests:                  # Minimum resources required to run the container
            memory: "64Mi"
            cpu: "50m"
          limits:                    # Maximum resources the container can use
            memory: "128Mi"
            cpu: "100m"

---
# Kubernetes Service to expose the frontend Deployment
apiVersion: v1                       # API version for Service objects
kind: Service                        # This resource is a Service

metadata:
  name: frontend-service             # Name of the Service
  namespace: nimc-demo               # Service will be created in the same namespace

spec:
  selector:
    app: frontend                    # Service will forward traffic to pods with this label
  ports:
    - protocol: TCP                  # Communication protocol
      port: 80                       # Service port exposed inside the cluster
      targetPort: 80                 # Port on the container that receives the traffic
      nodePort: 30018                # Port on each worker node for external access (NodePort)
  type: NodePort                     # Service type allowing external access via node port
